# backend/Dockerfile.dev
FROM openjdk:17-jdk-slim

WORKDIR /app

# Maven wrapper and dependencies
COPY pom.xml .
COPY .mvn .mvn/
COPY mvnw .
RUN ./mvnw dependency:go-offline -B

# 後続のステップでソースコードがマウントされることを想定
# アプリケーションの実行環境を準備
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]

EXPOSE 8080
EXPOSE 5005