# backend/Dockerfile.dev
FROM openjdk:17-jdk-slim

WORKDIR /app

# Maven wrapper and dependencies
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

# Source code
COPY src/ src/

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]